### ISSUE TITLE
React navigation v4 support

### ISSUE THREAD

**Issue by tankpower1** [benevbright/react-navigation-collapsible#124]
Can this package be used with react-navigation version 4?

**Comment by benevbright** [comment]
Please check out https://github.com/benevbright/react-navigation-collapsible#compatibility-
You can use `react-navigation-collapsible@3` for react-navigation v4, please note that it's not compatible when you use `react-navigation/stack@2`. 
And I don't recommend using it because there won't be a new update for it.

**Comment by tankpower1** [comment]
Ok, thank you.
