### ISSUE TITLE
Status bar and padding on Expo

### ISSUE THREAD

**Issue by Keplyx** [benevbright/react-navigation-collapsible#125]
When using expo with a translucent status bar, top padding is correct.

But when setting the status bar to Hidden or not Translucent (with app.json or with StatusBar class), padding top is not correct anymore. Seems like padding calculations still use the status bar height when it should be 0.

**Comment by benevbright** [comment]
Yes, I confirm this problem. 
The problem is that this module treats Expo always use `translucent` header and `react-native init` always not. 
https://github.com/benevbright/react-navigation-collapsible/blob/7b6825d34004cc17f365761c9a0c9c88c23bc440/src/utils.ts#L36

The status header height should be calculated according to the user option.

related with #116

**Comment by ozerty** [comment]
Hi @benevbright, do you think it will be fix soon ?
Thanks

**Comment by ozerty** [comment]
Not sure if it's related, but I have a specific height for my header which is 60.
I can notice when I use the createCollapsibleStack, a small part (on top) of my component goes behind the header.

**Comment by benevbright** [comment]
Hi, @ozerty 
There was a problem when using custom `headerStyle.height`. https://github.com/benevbright/react-navigation-collapsible/pull/130 This PR fixed it. 

I will fix the status problem soon and release them together.

**Comment by benevbright** [comment]
@Keplyx Please check this PR, https://github.com/benevbright/react-navigation-collapsible/pull/131.
It's not a smart solution but you can prevent the status height from being calculated.

**Comment by benevbright** [comment]
`v5.6.0` includes #130 and #131.
