### ISSUE TITLE
Transparent header in android

### ISSUE THREAD

**Issue by mopilo** [benevbright/react-navigation-collapsible#27]
They is no example for Android devices, on collapse the header becomes transparent and my header   title shows.

i noticed in your example you used iOSCollapsedColor, what do we use for android??

**Comment by benevbright** [comment]
Hi, `iOSCollapsedColor` is for iOS. 

You don't need it because you probably have an opaque status bar on Android unless you use expo
and the header will be just hidden to the top.

You can run this on the Android simulator. (It's expo)
(Expo Snack)[https://snack.expo.io/@benevbright/react-navigation-collapsible]

There is the example folder in this repo and it works on Android as well. (It's react-native init)

**Comment by benevbright** [comment]
In your case, you should use example for Expo.
But only difference is adding this line on your `app.js` or not.

```
/* Support Expo */
import { setExpoStatusBarHeight } from 'react-navigation-collapsible';
import { Constants } from 'expo';
setExpoStatusBarHeight(Constants.statusBarHeight);
```
This lines are for `Expo` or `create-react-native-app`.

**Comment by mopilo** [comment]
I'm confuse, i'm not using expo and am not sure if i can import constant from export since am using create-react-native-app

**Comment by benevbright** [comment]
Actually, `create-react-native-app` is one of the ways you use Expo. 
I believe you could find Expo dependency on your `package.json`.

**Comment by mopilo** [comment]
Okay thanks, i feel i gave the wrong impression, i meant react-native init  instead of create-react-native-app

**Comment by benevbright** [comment]
Oh, then you can use this example.

There is the example folder in this repo and it works on Android as well. (It's react-native init)
[Example](https://github.com/benevbright/react-navigation-collapsible/tree/master/example)
