### ISSUE TITLE
Extra Header for Android looks to be misaligned if height is set to 150+

### ISSUE THREAD

**Issue by jm90m** [benevbright/react-navigation-collapsible#35]
Hello, 

Great library btw. So on iOS this works perfectly for my use case, but on android the header is misaligned and opacity is wrong for default.

I was able to reproduce this issue in this snack - https://snack.expo.io/@benevbright/react-navigation-collapsible - with the following changes
```
const ExtraHeader = ({navigation}) => {  
  const { searchText } = navigation.state.params ? navigation.state.params : {};
  return (
    <View style={{width: '100%', height: '100%', paddingHorizontal: 20, paddingVertical: 10}}>
      <View style={{backgroundColor: 'white', flex: 1, borderRadius: 15, justifyContent: 'center'}}>
        <Text>TESTT</Text>
      </View>
    </View>
  );
}

const collapsibleParams = {
  extraHeader: ExtraHeader,
  extraHeaderStyle: {
    height: 150, 
    backgroundColor: '#061'
  }
}
```
How to reproduce:
- Set extraHeaderStyle height to something greater than 150+

**Comment by benevbright** [comment]
Hi, @jm90m .

Thanks for your report. 
It's probably caused by 
https://github.com/benevbright/react-navigation-collapsible/blob/9fcee463ed670e739399d47df4bdc2ed68fe0fe4/index.js#L30

I will look at this issue and fix it soon. 
In the meanwhile, you could increase the height in the above link in your `node_modules/react-navigation-collapsible/index.js` unless you are using expo only.

**Comment by jm90m** [comment]
@benevbright thanks for the reply, I am using expo only :(

**Comment by benevbright** [comment]
0.2.18 is released. 
This version should fix this bug. :)
Thanks again for your issue.
